apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  namespace: banking
spec:
  type: ClusterIP
  selector:
    app: ledger-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
