apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: banking
data:
  NODE_ENV: "production"
  SERVICE_NAME: "account-service"
  LOG_LEVEL: "info"
  ACCOUNT_SERVICE_PORT: "3001"
  DB_HOST: "replace-with-accounts-rds-endpoint"
  DB_PORT: "5432"
  DB_NAME: "accounts_db"
  DB_USER: "accounts_user"
  KAFKA_CLIENT_ID: "cn-banking-platform"
  KAFKA_SSL: "true"
  KAFKA_SASL_MECHANISM: "scram-sha-512"
  KAFKA_GROUP_ID_PREFIX: "cn-banking"
  KAFKA_TOPIC_ACCOUNT_CREATED: "bank.account.created"
