apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking
  labels:
    app.kubernetes.io/part-of: cn-banking
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "replace-with-access-secret"
  JWT_REFRESH_SECRET: "replace-with-refresh-secret"
  INTERNAL_SERVICE_SECRET: "replace-with-internal-service-secret"
  REDIS_URL: "rediss://:replace-with-redis-password@redis-endpoint:6379"
  REDIS_PASSWORD: "replace-with-redis-password"
  DB_ACCOUNTS_PASSWORD: "replace-with-accounts-db-password"
  DB_TRANSFERS_PASSWORD: "replace-with-transfers-db-password"
  KAFKA_BROKERS: "replace-with-msk-bootstrap-brokers"
  KAFKA_SASL_USERNAME: "cn_banking_app"
  KAFKA_SASL_PASSWORD: "replace-with-msk-scram-password"
  MONGODB_URI: "mongodb://replace-with-mongodb-compatible-endpoint:27017/banking_events"
  MONGODB_URL: "mongodb://replace-with-mongodb-compatible-endpoint:27017"
