apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-service-config
  namespace: banking
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  FRAUD_SERVICE_PORT: "3004"
  ACCOUNT_SERVICE_URL: "http://account-service:3001"
  MONGODB_DB_NAME: "banking_events"
  KAFKA_CLIENT_ID: "cn-banking-platform"
  KAFKA_SSL: "true"
  KAFKA_SASL_MECHANISM: "scram-sha-512"
  KAFKA_GROUP_ID_PREFIX: "cn-banking"
  KAFKA_TOPIC_TRANSFER_INITIATED: "bank.transfer.initiated"
  KAFKA_TOPIC_FRAUD_ALERT: "bank.fraud.alert"
