apiVersion: v1
kind: ConfigMap
metadata:
  name: web-portal-config
  namespace: banking
  labels:
    app: web-portal
data:
  config.js: |
    window.__CN_BANKING_CONFIG__ = {
      apiBaseUrl: "https://${PUBLIC_DOMAIN}"
    };
