apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: banking
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "8080"
  ACCOUNT_SERVICE_URL: "http://account-service:3001"
  TRANSFER_SERVICE_URL: "http://transfer-service:3002"
  LEDGER_SERVICE_URL: "http://ledger-service:3003"
  FRAUD_SERVICE_URL: "http://fraud-service:3004"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
